### ISSUE TITLE
I get an error when using this crate

### ISSUE THREAD

**Issue by mark-summerfield** [fltk-rs/fltk-grid#2]
Here are my deps:
```
[dependencies]
...
fltk-grid = "^0.1"

[dependencies.fltk]
version = "^1.3"
features = [ "no-pango",]
git = "https://github.com/fltk-rs/fltk-rs"
```
And here's the error (on Linux; but same on Windows):
```
    Updating crates.io index
error: failed to select a version for `fltk-sys`.
    ... required by package `fltk v1.3.0`
    ... which satisfies dependency `fltk = "^1.3"` of package `fltk-grid v0.1.0`
    ... which satisfies dependency `fltk-grid = "^0.1"` of package `diffpdf v7.0.0-a1 (/home/mark/commercial/comparepdfcmd2/diffpdf)`
versions that meet the requirements `=1.3.0` are: 1.3.0

the package `fltk-sys` links to the native library `fltk`, but it conflicts with a previous package which links to `fltk` as well:
package `fltk-sys v1.3.28 (https://github.com/fltk-rs/fltk-rs#350b5a67)`
    ... which satisfies git dependency `fltk-sys` (locked to 1.3.28) of package `fltk v1.3.28 (https://github.com/fltk-rs/fltk-rs#350b5a67)`
    ... which satisfies git dependency `fltk` (locked to 1.3.28) of package `diffpdf v7.0.0-a1 (/home/mark/commercial/comparepdfcmd2/diffpdf)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='fltk-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `fltk-sys` which could resolve this conflict
```

**Comment by MoAlyousef** [comment]
I get the same with the same deps. I think both (fltk and fltk-grid) need to be pulled from crates.io registry for Cargo's dependency resolution to succeed. I'll publish a new version of fltk-rs tomorrow hopefully. Just need to pull some fixes from FLTK first. Or another possiblity is to use patch:
```toml
[dependencies]
...
fltk-grid = "^0.1"

[dependencies.fltk]
version = "^1.3"
features = [ "no-pango",]
git = "https://github.com/fltk-rs/fltk-rs"

[patch.crates-io]
fltk = { git = 'https://github.com/fltk-rs/fltk-rs' }
```
This should cause fltk-grid to also depend on the github version of fltk.
